In [1]:
import pandas as pd

results = pd.read_csv("../data/raw/international_results/results.csv")

results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [2]:
results.shape

(49505, 9)

In [3]:
results.dtypes

date              str
home_team         str
away_team         str
home_score    float64
away_score    float64
tournament        str
city              str
country           str
neutral          bool
dtype: object

In [4]:
results.isnull().sum()

date          0
home_team     0
away_team     0
home_score    4
away_score    4
tournament    0
city          0
country       0
neutral       0
dtype: int64

In [6]:
results.duplicated().sum()

np.int64(0)

In [8]:
duplicates = results[results.duplicated()]
duplicates.head()

Empty DataFrame
Columns: [date, home_team, away_team, home_score, away_score, tournament, city, country, neutral]
Index: []

In [9]:
results["tournament"].value_counts()

tournament
Friendly                                18388
FIFA World Cup qualification             8771
UEFA Euro qualification                  2824
African Cup of Nations qualification     2327
FIFA World Cup                           1064
                                        ...
Copa Confraternidad                         1
Benedikt Fontana Cup                        1
ConIFA Challenger Cup                       1
CONIFA World Cup qualification              1
South Asian Super Cup                       1
Name: count, Length: 200, dtype: int64

In [10]:
results["neutral"].value_counts()

neutral
False    36360
True     13145
Name: count, dtype: int64

In [12]:
results["date"] = pd.to_datetime(results["date"])

In [14]:
print(results["date"].min())
print(results["date"].max())

1872-11-30 00:00:00
2026-07-11 00:00:00

In [16]:
results["home_team"].sort_values().unique()

<StringArray>
[      'Abkhazia',    'Afghanistan',        'Albania',       'Alderney',
        'Algeria', 'American Samoa',      'Andalusia',        'Andorra',
         'Angola',       'Anguilla',
 ...
          'Yemen',      'Yemen DPR',       'Ynys Môn',      'Yorkshire',
  'Yoruba Nation',     'Yugoslavia',         'Zambia',       'Zanzibar',
       'Zimbabwe',  'Åland Islands']
Length: 327, dtype: str

In [18]:
results["away_team"].sort_values().unique()

<StringArray>
[      'Abkhazia',    'Afghanistan',        'Albania',       'Alderney',
        'Algeria',      'Ambazonia', 'American Samoa',      'Andalusia',
        'Andorra',         'Angola',
 ...
 'Western Sahara',          'Yemen',      'Yemen DPR',       'Ynys Môn',
      'Yorkshire',     'Yugoslavia',         'Zambia',       'Zanzibar',
       'Zimbabwe',  'Åland Islands']
Length: 321, dtype: str

In [19]:
results.describe()

                             date    home_score    away_score
count                       49505  49501.000000  49501.000000
mean   1994-05-29 04:51:36.414503      1.757197      1.181936
min           1872-11-30 00:00:00      0.000000      0.000000
25%           1980-09-12 00:00:00      1.000000      0.000000
50%           2000-07-16 00:00:00      1.000000      1.000000
75%           2013-07-21 00:00:00      2.000000      2.000000
max           2026-07-11 00:00:00     31.000000     21.000000
std                           NaN      1.773821      1.401655

In [20]:
results["tournament"].unique()

<StringArray>
[                                         'Friendly',
                         'British Home Championship',
                              'Évence Coppée Trophy',
                                      'Muratti Vase',
                                       'Copa Lipton',
                                       'Copa Newton',
                       'Copa Premio Honor Argentino',
                                     'Olympic Games',
                        'Copa Premio Honor Uruguayo',
                    'Far Eastern Championship Games',
 ...
                                     'Mapinduzi Cup',
                                   'Canadian Shield',
                           'Outrigger Challenge Cup',
                             'South Asian Super Cup',
                                   'CONCACAF Series',
                          'Al Ain International Cup',
              'Morocco, Capital of African Football',
                                  'Mukuru 4 Nations',
 'Diamond Jubilee International Football Tournament',
                                   'Tri-Nations Cup']
Length: 200, dtype: str