In [1]:
import pandas as pd

team_form = pd.read_csv("../data/raw/match_features/teams_form.csv")

team_form.head()

          team  match_date  avg_goals_scored  avg_goals_conceded  win_rate
0  Afghanistan  1941-08-24          1.500000            1.500000      0.33
1  Afghanistan  1941-08-31          0.000000            0.000000      0.00
2  Afghanistan  1948-06-03          0.500000            1.500000      0.00
3  Afghanistan  1948-07-26          0.333333            2.333333      0.00
4  Afghanistan  1949-10-26          0.250000            3.250000      0.00

In [2]:
print("Shape:")
print(team_form.shape)

print("\nColumns:")
print(team_form.columns.tolist())

print("\nData Types:")
team_form.info()

Shape:
(102094, 5)

Columns:
['team', 'match_date', 'avg_goals_scored', 'avg_goals_conceded', 'win_rate']

Data Types:
<class 'pandas.DataFrame'>
RangeIndex: 102094 entries, 0 to 102093
Data columns (total 5 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   team                102094 non-null  str
 1   match_date          102094 non-null  str
 2   avg_goals_scored    102094 non-null  float64
 3   avg_goals_conceded  102094 non-null  float64
 4   win_rate            102094 non-null  float64
dtypes: float64(3), str(2)
memory usage: 3.9 MB

In [3]:
print("\nMissing Values:")
display(team_form.isnull().sum())

print("\nDuplicate Rows:")
print(team_form.duplicated().sum())

Missing Values:

team                  0
match_date            0
avg_goals_scored      0
avg_goals_conceded    0
win_rate              0
dtype: int64

Duplicate Rows:
0

In [4]:
team_form.describe(include="all")

,team,match_date,avg_goals_scored,avg_goals_conceded,win_rate
count,102094,102094,102094.000000,102094.000000,102094.000000
unique,247,17149,NaN,NaN,NaN
top,England,2012-02-29,NaN,NaN,NaN
freq,1148,132,NaN,NaN,NaN
mean,NaN,NaN,1.462041,1.466210,0.385328
std,NaN,NaN,0.876040,1.008109,0.252024
min,NaN,NaN,0.000000,0.000000,0.000000
25%,NaN,NaN,0.800000,0.800000,0.200000
50%,NaN,NaN,1.400000,1.200000,0.400000
75%,NaN,NaN,1.800000,1.800000,0.600000
max,NaN,NaN,13.600000,24.000000,1.000000

In [5]:
for col in team_form.columns:
    print("=" * 60)
    print(col)
    print(team_form[col].head())

============================================================
team
0    Afghanistan
1    Afghanistan
2    Afghanistan
3    Afghanistan
4    Afghanistan
Name: team, dtype: str
============================================================
match_date
0    1941-08-24
1    1941-08-31
2    1948-06-03
3    1948-07-26
4    1949-10-26
Name: match_date, dtype: str
============================================================
avg_goals_scored
0    1.500000
1    0.000000
2    0.500000
3    0.333333
4    0.250000
Name: avg_goals_scored, dtype: float64
============================================================
avg_goals_conceded
0    1.500000
1    0.000000
2    1.500000
3    2.333333
4    3.250000
Name: avg_goals_conceded, dtype: float64
============================================================
win_rate
0    0.33
1    0.00
2    0.00
3    0.00
4    0.00
Name: win_rate, dtype: float64

In [2]:
import pandas as pd

team_match_features = pd.read_csv("../data/raw/match_features/teams_match_features.csv")

team_match_features.head()

,home_elo,away_elo,elo_diff,home_avg_overall,home_max_overall,home_avg_attack,home_avg_defense,home_avg_pace,home_avg_shooting,home_avg_passing,...,away_form_win_rate,is_neutral,is_world_cup,is_continental,home_goals,away_goals,_home_team,_away_team,_date,_tournament
0,1500.000000,1500.000000,0.000000,74.285714,76,74.50,74.250000,71.083333,69.500000,69.583333,...,0.330000,0,0,0,0,0,Scotland,England,1872-11-30,Friendly
1,1500.000000,1500.000000,0.000000,81.500000,86,82.25,81.222222,73.538462,69.923077,71.307692,...,0.000000,0,0,0,4,2,England,Scotland,1873-03-08,Friendly
2,1484.000000,1516.000000,-32.000000,74.285714,76,74.50,74.250000,71.083333,69.500000,69.583333,...,0.500000,0,0,0,2,1,Scotland,England,1874-03-07,Friendly
3,1498.530498,1501.469502,-2.939003,81.500000,86,82.25,81.222222,73.538462,69.923077,71.307692,...,0.333333,0,0,0,2,2,England,Scotland,1875-03-06,Friendly
4,1501.334159,1498.665841,2.668317,74.285714,76,74.50,74.250000,71.083333,69.500000,69.583333,...,0.250000,0,0,0,3,0,Scotland,England,1876-03-04,Friendly

In [3]:
print("Shape:")
print(team_match_features.shape)

print("\nColumns:")
print(team_match_features.columns.tolist())

print("\nData Types:")
team_match_features.info()

Shape:
(43364, 35)

Columns:
['home_elo', 'away_elo', 'elo_diff', 'home_avg_overall', 'home_max_overall', 'home_avg_attack', 'home_avg_defense', 'home_avg_pace', 'home_avg_shooting', 'home_avg_passing', 'away_avg_overall', 'away_max_overall', 'away_avg_attack', 'away_avg_defense', 'away_avg_pace', 'away_avg_shooting', 'away_avg_passing', 'overall_diff', 'attack_diff', 'defense_diff', 'home_form_scored', 'home_form_conceded', 'home_form_win_rate', 'away_form_scored', 'away_form_conceded', 'away_form_win_rate', 'is_neutral', 'is_world_cup', 'is_continental', 'home_goals', 'away_goals', '_home_team', '_away_team', '_date', '_tournament']

Data Types:
<class 'pandas.DataFrame'>
RangeIndex: 43364 entries, 0 to 43363
Data columns (total 35 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   home_elo            43364 non-null  float64
 1   away_elo            43364 non-null  float64
 2   elo_diff            43364 non-null  float64
 3   home_avg_overall    43364 non-null  float64
 4   home_max_overall    43364 non-null  int64
 5   home_avg_attack     43364 non-null  float64
 6   home_avg_defense    43364 non-null  float64
 7   home_avg_pace       42667 non-null  float64
 8   home_avg_shooting   42667 non-null  float64
 9   home_avg_passing    42667 non-null  float64
 10  away_avg_overall    43364 non-null  float64
 11  away_max_overall    43364 non-null  int64
 12  away_avg_attack     43364 non-null  float64
 13  away_avg_defense    43364 non-null  float64
 14  away_avg_pace       42563 non-null  float64
 15  away_avg_shooting   42563 non-null  float64
 16  away_avg_passing    42563 non-null  float64
 17  overall_diff        43364 non-null  float64
 18  attack_diff         43364 non-null  float64
 19  defense_diff        43364 non-null  float64
 20  home_form_scored    43364 non-null  float64
 21  home_form_conceded  43364 non-null  float64
 22  home_form_win_rate  43364 non-null  float64
 23  away_form_scored    43364 non-null  float64
 24  away_form_conceded  43364 non-null  float64
 25  away_form_win_rate  43364 non-null  float64
 26  is_neutral          43364 non-null  int64
 27  is_world_cup        43364 non-null  int64
 28  is_continental      43364 non-null  int64
 29  home_goals          43364 non-null  int64
 30  away_goals          43364 non-null  int64
 31  _home_team          43364 non-null  str
 32  _away_team          43364 non-null  str
 33  _date               43364 non-null  str
 34  _tournament         43364 non-null  str
dtypes: float64(24), int64(7), str(4)
memory usage: 11.6 MB

In [4]:
print("\nMissing Values:")
display(team_match_features.isnull().sum())

print("\nDuplicate Rows:")
print(team_match_features.duplicated().sum())

Missing Values:

home_elo                0
away_elo                0
elo_diff                0
home_avg_overall        0
home_max_overall        0
home_avg_attack         0
home_avg_defense        0
home_avg_pace         697
home_avg_shooting     697
home_avg_passing      697
away_avg_overall        0
away_max_overall        0
away_avg_attack         0
away_avg_defense        0
away_avg_pace         801
away_avg_shooting     801
away_avg_passing      801
overall_diff            0
attack_diff             0
defense_diff            0
home_form_scored        0
home_form_conceded      0
home_form_win_rate      0
away_form_scored        0
away_form_conceded      0
away_form_win_rate      0
is_neutral              0
is_world_cup            0
is_continental          0
home_goals              0
away_goals              0
_home_team              0
_away_team              0
_date                   0
_tournament             0
dtype: int64

Duplicate Rows:
0

In [5]:
team_match_features.describe(include="all")

,home_elo,away_elo,elo_diff,home_avg_overall,home_max_overall,home_avg_attack,home_avg_defense,home_avg_pace,home_avg_shooting,home_avg_passing,...,away_form_win_rate,is_neutral,is_world_cup,is_continental,home_goals,away_goals,_home_team,_away_team,_date,_tournament
count,43364.000000,43364.000000,43364.000000,43364.000000,43364.000000,43364.000000,43364.000000,42667.000000,42667.000000,42667.000000,...,43364.000000,43364.000000,43364.0,43364.000000,43364.000000,43364.000000,43364,43364,43364,43364
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,180,180,15699,213
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Brazil,Sweden,2012-02-29,Friendly
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,633,563,61,15272
mean,1598.044157,1578.072757,19.971399,71.077261,76.485956,71.269657,71.003682,72.269776,59.686770,62.383452,...,0.384427,0.241329,0.0,0.010631,1.852989,0.987155,NaN,NaN,NaN,NaN
std,162.443375,164.836725,183.697952,7.680750,9.098305,7.971538,7.588874,5.037509,9.079159,9.186571,...,0.251284,0.427894,0.0,0.102558,1.678215,1.190325,NaN,NaN,NaN,NaN
min,952.188855,940.490222,-997.218420,51.000000,51.000000,49.000000,50.000000,43.000000,21.000000,29.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
25%,1487.281967,1469.296294,-93.935915,65.166667,70.000000,65.500000,65.285714,69.166667,54.250000,55.384615,...,0.200000,0.000000,0.0,0.000000,1.000000,0.000000,NaN,NaN,NaN,NaN
50%,1593.671278,1576.750306,19.450494,71.607143,77.000000,71.857143,72.000000,72.750000,61.846154,63.846154,...,0.400000,0.000000,0.0,0.000000,2.000000,1.000000,NaN,NaN,NaN,NaN
75%,1704.918241,1688.865926,134.781590,76.857143,83.000000,76.750000,76.600000,75.384615,66.500000,68.800000,...,0.600000,0.000000,0.0,0.000000,3.000000,1.000000,NaN,NaN,NaN,NaN
max,2104.760786,2109.115688,972.098675,87.285714,94.000000,88.666667,87.750000,91.000000,80.000000,81.846154,...,1.000000,1.000000,0.0,1.000000,21.000000,15.000000,NaN,NaN,NaN,NaN

In [6]:
for col in team_match_features.columns:
    print("=" * 60)
    print(col)
    print(team_match_features[col].head())

============================================================
home_elo
0    1500.000000
1    1500.000000
2    1484.000000
3    1498.530498
4    1501.334159
Name: home_elo, dtype: float64
============================================================
away_elo
0    1500.000000
1    1500.000000
2    1516.000000
3    1501.469502
4    1498.665841
Name: away_elo, dtype: float64
============================================================
elo_diff
0     0.000000
1     0.000000
2   -32.000000
3    -2.939003
4     2.668317
Name: elo_diff, dtype: float64
============================================================
home_avg_overall
0    74.285714
1    81.500000
2    74.285714
3    81.500000
4    74.285714
Name: home_avg_overall, dtype: float64
============================================================
home_max_overall
0    76
1    86
2    76
3    86
4    76
Name: home_max_overall, dtype: int64
============================================================
home_avg_attack
0    74.50
1    82.25
2    74.50
3    82.25
4    74.50
Name: home_avg_attack, dtype: float64
============================================================
home_avg_defense
0    74.250000
1    81.222222
2    74.250000
3    81.222222
4    74.250000
Name: home_avg_defense, dtype: float64
============================================================
home_avg_pace
0    71.083333
1    73.538462
2    71.083333
3    73.538462
4    71.083333
Name: home_avg_pace, dtype: float64
============================================================
home_avg_shooting
0    69.500000
1    69.923077
2    69.500000
3    69.923077
4    69.500000
Name: home_avg_shooting, dtype: float64
============================================================
home_avg_passing
0    69.583333
1    71.307692
2    69.583333
3    71.307692
4    69.583333
Name: home_avg_passing, dtype: float64
============================================================
away_avg_overall
0    81.500000
1    74.285714
2    81.500000
3    74.285714
4    81.500000
Name: away_avg_overall, dtype: float64
============================================================
away_max_overall
0    86
1    76
2    86
3    76
4    86
Name: away_max_overall, dtype: int64
============================================================
away_avg_attack
0    82.25
1    74.50
2    82.25
3    74.50
4    82.25
Name: away_avg_attack, dtype: float64
============================================================
away_avg_defense
0    81.222222
1    74.250000
2    81.222222
3    74.250000
4    81.222222
Name: away_avg_defense, dtype: float64
============================================================
away_avg_pace
0    73.538462
1    71.083333
2    73.538462
3    71.083333
4    73.538462
Name: away_avg_pace, dtype: float64
============================================================
away_avg_shooting
0    69.923077
1    69.500000
2    69.923077
3    69.500000
4    69.923077
Name: away_avg_shooting, dtype: float64
============================================================
away_avg_passing
0    71.307692
1    69.583333
2    71.307692
3    69.583333
4    71.307692
Name: away_avg_passing, dtype: float64
============================================================
overall_diff
0   -7.214286
1    7.214286
2   -7.214286
3    7.214286
4   -7.214286
Name: overall_diff, dtype: float64
============================================================
attack_diff
0   -7.75
1    7.75
2   -7.75
3    7.75
4   -7.75
Name: attack_diff, dtype: float64
============================================================
defense_diff
0   -6.972222
1    6.972222
2   -6.972222
3    6.972222
4   -6.972222
Name: defense_diff, dtype: float64
============================================================
home_form_scored
0    1.500000
1    0.000000
2    1.000000
3    1.666667
4    1.500000
Name: home_form_scored, dtype: float64
============================================================
home_form_conceded
0    1.500000
1    0.000000
2    2.000000
3    1.333333
4    1.750000
Name: home_form_conceded, dtype: float64
============================================================
home_form_win_rate
0    0.330000
1    0.000000
2    0.000000
3    0.333333
4    0.250000
Name: home_form_win_rate, dtype: float64
============================================================
away_form_scored
0    1.500000
1    0.000000
2    2.000000
3    1.333333
4    1.750000
Name: away_form_scored, dtype: float64
============================================================
away_form_conceded
0    1.500000
1    0.000000
2    1.000000
3    1.666667
4    1.500000
Name: away_form_conceded, dtype: float64
============================================================
away_form_win_rate
0    0.330000
1    0.000000
2    0.500000
3    0.333333
4    0.250000
Name: away_form_win_rate, dtype: float64
============================================================
is_neutral
0    0
1    0
2    0
3    0
4    0
Name: is_neutral, dtype: int64
============================================================
is_world_cup
0    0
1    0
2    0
3    0
4    0
Name: is_world_cup, dtype: int64
============================================================
is_continental
0    0
1    0
2    0
3    0
4    0
Name: is_continental, dtype: int64
============================================================
home_goals
0    0
1    4
2    2
3    2
4    3
Name: home_goals, dtype: int64
============================================================
away_goals
0    0
1    2
2    1
3    2
4    0
Name: away_goals, dtype: int64
============================================================
_home_team
0    Scotland
1     England
2    Scotland
3     England
4    Scotland
Name: _home_team, dtype: str
============================================================
_away_team
0     England
1    Scotland
2     England
3    Scotland
4     England
Name: _away_team, dtype: str
============================================================
_date
0    1872-11-30
1    1873-03-08
2    1874-03-07
3    1875-03-06
4    1876-03-04
Name: _date, dtype: str
============================================================
_tournament
0    Friendly
1    Friendly
2    Friendly
3    Friendly
4    Friendly
Name: _tournament, dtype: str

In [7]:
match_features = pd.read_csv("../data/raw/match_features/teams_match_features.csv")

match_features.head()

,home_elo,away_elo,elo_diff,home_avg_overall,home_max_overall,home_avg_attack,home_avg_defense,home_avg_pace,home_avg_shooting,home_avg_passing,...,away_form_win_rate,is_neutral,is_world_cup,is_continental,home_goals,away_goals,_home_team,_away_team,_date,_tournament
0,1500.000000,1500.000000,0.000000,74.285714,76,74.50,74.250000,71.083333,69.500000,69.583333,...,0.330000,0,0,0,0,0,Scotland,England,1872-11-30,Friendly
1,1500.000000,1500.000000,0.000000,81.500000,86,82.25,81.222222,73.538462,69.923077,71.307692,...,0.000000,0,0,0,4,2,England,Scotland,1873-03-08,Friendly
2,1484.000000,1516.000000,-32.000000,74.285714,76,74.50,74.250000,71.083333,69.500000,69.583333,...,0.500000,0,0,0,2,1,Scotland,England,1874-03-07,Friendly
3,1498.530498,1501.469502,-2.939003,81.500000,86,82.25,81.222222,73.538462,69.923077,71.307692,...,0.333333,0,0,0,2,2,England,Scotland,1875-03-06,Friendly
4,1501.334159,1498.665841,2.668317,74.285714,76,74.50,74.250000,71.083333,69.500000,69.583333,...,0.250000,0,0,0,3,0,Scotland,England,1876-03-04,Friendly

In [9]:
match_features.columns.tolist()

['home_elo',
 'away_elo',
 'elo_diff',
 'home_avg_overall',
 'home_max_overall',
 'home_avg_attack',
 'home_avg_defense',
 'home_avg_pace',
 'home_avg_shooting',
 'home_avg_passing',
 'away_avg_overall',
 'away_max_overall',
 'away_avg_attack',
 'away_avg_defense',
 'away_avg_pace',
 'away_avg_shooting',
 'away_avg_passing',
 'overall_diff',
 'attack_diff',
 'defense_diff',
 'home_form_scored',
 'home_form_conceded',
 'home_form_win_rate',
 'away_form_scored',
 'away_form_conceded',
 'away_form_win_rate',
 'is_neutral',
 'is_world_cup',
 'is_continental',
 'home_goals',
 'away_goals',
 '_home_team',
 '_away_team',
 '_date',
 '_tournament']

In [11]:
match_features.shape

(43364, 35)

In [12]:
match_features.isnull().sum()

home_elo                0
away_elo                0
elo_diff                0
home_avg_overall        0
home_max_overall        0
home_avg_attack         0
home_avg_defense        0
home_avg_pace         697
home_avg_shooting     697
home_avg_passing      697
away_avg_overall        0
away_max_overall        0
away_avg_attack         0
away_avg_defense        0
away_avg_pace         801
away_avg_shooting     801
away_avg_passing      801
overall_diff            0
attack_diff             0
defense_diff            0
home_form_scored        0
home_form_conceded      0
home_form_win_rate      0
away_form_scored        0
away_form_conceded      0
away_form_win_rate      0
is_neutral              0
is_world_cup            0
is_continental          0
home_goals              0
away_goals              0
_home_team              0
_away_team              0
_date                   0
_tournament             0
dtype: int64

In [13]:
match_features.duplicated().sum()

np.int64(0)

In [14]:
match_features.head()

,home_elo,away_elo,elo_diff,home_avg_overall,home_max_overall,home_avg_attack,home_avg_defense,home_avg_pace,home_avg_shooting,home_avg_passing,...,away_form_win_rate,is_neutral,is_world_cup,is_continental,home_goals,away_goals,_home_team,_away_team,_date,_tournament
0,1500.000000,1500.000000,0.000000,74.285714,76,74.50,74.250000,71.083333,69.500000,69.583333,...,0.330000,0,0,0,0,0,Scotland,England,1872-11-30,Friendly
1,1500.000000,1500.000000,0.000000,81.500000,86,82.25,81.222222,73.538462,69.923077,71.307692,...,0.000000,0,0,0,4,2,England,Scotland,1873-03-08,Friendly
2,1484.000000,1516.000000,-32.000000,74.285714,76,74.50,74.250000,71.083333,69.500000,69.583333,...,0.500000,0,0,0,2,1,Scotland,England,1874-03-07,Friendly
3,1498.530498,1501.469502,-2.939003,81.500000,86,82.25,81.222222,73.538462,69.923077,71.307692,...,0.333333,0,0,0,2,2,England,Scotland,1875-03-06,Friendly
4,1501.334159,1498.665841,2.668317,74.285714,76,74.50,74.250000,71.083333,69.500000,69.583333,...,0.250000,0,0,0,3,0,Scotland,England,1876-03-04,Friendly