In [2]:
import pandas as pd

results = pd.read_csv("../data/interim/results_clean.csv")
elo = pd.read_csv("../data/interim/elo_clean.csv")
rankings = pd.read_csv("../data/interim/rankings_clean.csv")
match_features = pd.read_csv("../data/interim/match_features_clean.csv")

In [3]:
print(results.columns.tolist())
print(elo.columns.tolist())
print(rankings.columns.tolist())
print(match_features.columns.tolist())

['date', 'home_team', 'away_team', 'home_score', 'away_score', 'tournament', 'city', 'country', 'neutral']
['date', 'team', 'rating', 'change']
['rank', 'country_abrv', 'total_points', 'previous_points', 'rank_change', 'confederation', 'rank_date', 'team']
['home_elo', 'away_elo', 'elo_diff', 'home_avg_overall', 'home_max_overall', 'home_avg_attack', 'home_avg_defense', 'home_avg_pace', 'home_avg_shooting', 'home_avg_passing', 'away_avg_overall', 'away_max_overall', 'away_avg_attack', 'away_avg_defense', 'away_avg_pace', 'away_avg_shooting', 'away_avg_passing', 'overall_diff', 'attack_diff', 'defense_diff', 'home_form_scored', 'home_form_conceded', 'home_form_win_rate', 'away_form_scored', 'away_form_conceded', 'away_form_win_rate', 'is_neutral', 'is_world_cup', 'is_continental', 'home_goals', 'away_goals', '_home_team', '_away_team', '_date', '_tournament']

In [4]:
display(results.head())
display(elo.head())
display(rankings.head())
display(match_features.head())

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

         date      team  rating  change
0  1872-11-30   England  2003.0       3
1  1872-11-30  Scotland  1997.0      -3
2  1873-03-08   England  2014.0      11
3  1873-03-08  Scotland  1986.0     -11
4  1874-03-07   England  2006.0      -8

,rank,country_abrv,total_points,previous_points,rank_change,confederation,rank_date,team
0,1,GER,57.0,0.0,0,UEFA,1992-12-31,Germany
1,96,SYR,11.0,0.0,0,AFC,1992-12-31,Syria
2,97,BFA,11.0,0.0,0,CAF,1992-12-31,Burkina Faso
3,99,LVA,10.0,0.0,0,UEFA,1992-12-31,Latvia
4,100,BDI,10.0,0.0,0,CAF,1992-12-31,Burundi

,home_elo,away_elo,elo_diff,home_avg_overall,home_max_overall,home_avg_attack,home_avg_defense,home_avg_pace,home_avg_shooting,home_avg_passing,...,away_form_win_rate,is_neutral,is_world_cup,is_continental,home_goals,away_goals,_home_team,_away_team,_date,_tournament
0,1500.000000,1500.000000,0.000000,74.285714,76,74.50,74.250000,71.083333,69.500000,69.583333,...,0.330000,0,0,0,0,0,Scotland,England,1872-11-30,Friendly
1,1500.000000,1500.000000,0.000000,81.500000,86,82.25,81.222222,73.538462,69.923077,71.307692,...,0.000000,0,0,0,4,2,England,Scotland,1873-03-08,Friendly
2,1484.000000,1516.000000,-32.000000,74.285714,76,74.50,74.250000,71.083333,69.500000,69.583333,...,0.500000,0,0,0,2,1,Scotland,England,1874-03-07,Friendly
3,1498.530498,1501.469502,-2.939003,81.500000,86,82.25,81.222222,73.538462,69.923077,71.307692,...,0.333333,0,0,0,2,2,England,Scotland,1875-03-06,Friendly
4,1501.334159,1498.665841,2.668317,74.285714,76,74.50,74.250000,71.083333,69.500000,69.583333,...,0.250000,0,0,0,3,0,Scotland,England,1876-03-04,Friendly

In [5]:
results.dtypes

date              str
home_team         str
away_team         str
home_score    float64
away_score    float64
tournament        str
city              str
country           str
neutral          bool
dtype: object

In [6]:
elo.dtypes

date          str
team          str
rating    float64
change      int64
dtype: object

In [7]:
rankings.dtypes

rank                 int64
country_abrv           str
total_points       float64
previous_points    float64
rank_change          int64
confederation          str
rank_date              str
team                   str
dtype: object

In [8]:
match_features.dtypes

home_elo              float64
away_elo              float64
elo_diff              float64
home_avg_overall      float64
home_max_overall        int64
home_avg_attack       float64
home_avg_defense      float64
home_avg_pace         float64
home_avg_shooting     float64
home_avg_passing      float64
away_avg_overall      float64
away_max_overall        int64
away_avg_attack       float64
away_avg_defense      float64
away_avg_pace         float64
away_avg_shooting     float64
away_avg_passing      float64
overall_diff          float64
attack_diff           float64
defense_diff          float64
home_form_scored      float64
home_form_conceded    float64
home_form_win_rate    float64
away_form_scored      float64
away_form_conceded    float64
away_form_win_rate    float64
is_neutral              int64
is_world_cup            int64
is_continental          int64
home_goals              int64
away_goals              int64
_home_team                str
_away_team                str
_date                     str
_tournament               str
dtype: object

In [9]:
print("Results Home Team")
print(results["home_team"].sample(10).tolist())

Results Home Team
['Panama', 'Mexico', 'Venezuela', 'Nepal', 'DR Congo', 'England', 'Saudi Arabia', 'Palestine', 'Oman', 'Paraguay']

In [10]:
print("Results Away Team")
print(results["away_team"].sample(10).tolist())

Results Away Team
['Lithuania', 'DR Congo', 'Latvia', 'Singapore', 'Northern Ireland', 'Seychelles', 'Guatemala', 'Australia', 'Botswana', 'Colombia']

In [11]:
print("Elo Team")
print(elo["team"].sample(10).tolist())

Elo Team
['Benin', 'Malawi', 'Brazil', 'Denmark', 'Senegal', 'Australia', 'Scotland', 'Myanmar', 'Syria', 'Bhutan']

In [12]:
print("Rankings Team")
print(rankings["team"].sample(10).tolist())

Rankings Team
['Kazakhstan', 'Nicaragua', 'Morocco', 'Hong Kong', 'Curaçao', 'Kyrgyzstan', 'Palestine', 'Botswana', 'Eswatini', 'San Marino']

In [13]:
print("Match Features Home Team")
print(match_features["_home_team"].sample(10).tolist())

Match Features Home Team
['Russia', 'Kuwait', 'Peru', 'United Arab Emirates', 'Egypt', 'Bolivia', 'Israel', 'Malta', 'Rwanda', 'Northern Ireland']

In [14]:
print("Match Features Away Team")
print(match_features["_away_team"].sample(10).tolist())

Match Features Away Team
['Algeria', 'Hungary', 'Zimbabwe', 'United States', 'Uzbekistan', 'Colombia', 'Senegal', 'Bolivia', 'Norway', 'Peru']

In [15]:
results["date"] = pd.to_datetime(results["date"])
elo["date"] = pd.to_datetime(elo["date"])
rankings["rank_date"] = pd.to_datetime(rankings["rank_date"])
match_features["_date"] = pd.to_datetime(match_features["_date"])

In [17]:
elo.rename(columns={
    "team": "elo_team"
}, inplace=True)

In [18]:
rankings.rename(columns={
    "team": "ranking_team",
    "rank_date": "date"
}, inplace=True)

In [20]:
match_features.rename(columns={
    "_home_team": "home_team",
    "_away_team": "away_team",
    "_date": "date",
    "_tournament": "tournament"
}, inplace=True)

In [21]:
print(results.columns)
print(elo.columns)
print(rankings.columns)
print(match_features.columns)

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='str')
Index(['date', 'elo_team', 'rating', 'change'], dtype='str')
Index(['rank', 'country_abrv', 'total_points', 'previous_points',
       'rank_change', 'confederation', 'date', 'ranking_team'],
      dtype='str')
Index(['home_elo', 'away_elo', 'elo_diff', 'home_avg_overall',
       'home_max_overall', 'home_avg_attack', 'home_avg_defense',
       'home_avg_pace', 'home_avg_shooting', 'home_avg_passing',
       'away_avg_overall', 'away_max_overall', 'away_avg_attack',
       'away_avg_defense', 'away_avg_pace', 'away_avg_shooting',
       'away_avg_passing', 'overall_diff', 'attack_diff', 'defense_diff',
       'home_form_scored', 'home_form_conceded', 'home_form_win_rate',
       'away_form_scored', 'away_form_conceded', 'away_form_win_rate',
       'is_neutral', 'is_world_cup', 'is_continental', 'home_goals',
       'away_goals', 'home_team', 'away_team', 'date', 'tournament'],
      dtype='str')

In [23]:
merged = results.merge(
    match_features,
    on=["date", "home_team", "away_team", "tournament"],
    how="left"
)

print(merged.shape)
merged.head()

(49501, 40)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,home_elo,...,home_form_conceded,home_form_win_rate,away_form_scored,away_form_conceded,away_form_win_rate,is_neutral,is_world_cup,is_continental,home_goals,away_goals
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False,1500.000000,...,1.500000,0.330000,1.500000,1.500000,0.330000,0.0,0.0,0.0,0.0,0.0
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False,1500.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,4.0,2.0
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False,1484.000000,...,2.000000,0.000000,2.000000,1.000000,0.500000,0.0,0.0,0.0,2.0,1.0
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False,1498.530498,...,1.333333,0.333333,1.333333,1.666667,0.333333,0.0,0.0,0.0,2.0,2.0
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False,1501.334159,...,1.750000,0.250000,1.750000,1.500000,0.250000,0.0,0.0,0.0,3.0,0.0

In [24]:
merged.isnull().sum().sort_values(ascending=False).head(15)

home_avg_pace         34502
home_avg_defense      34502
home_max_overall      34502
home_avg_attack       34502
home_avg_overall      34502
elo_diff              34502
away_elo              34502
home_elo              34502
away_form_scored      34502
away_avg_passing      34502
overall_diff          34502
attack_diff           34502
defense_diff          34502
home_form_scored      34502
home_form_conceded    34502
dtype: int64

In [25]:
print("Results:", len(results))
print("Match Features:", len(match_features))

Results: 49501
Match Features: 43364

In [26]:
print(match_features["tournament"].value_counts().head(20))

tournament
Friendly                          15272
World Cup qualifier                7054
European Championship qual         2724
African Nations Cup qualifier      2037
Friendly tournament                1743
World Cup                           928
African Nations Cup                 763
Olympic Games qualifier             657
Asian Cup qualifier                 635
British Championship                515
CECAFA Cup                          508
Copa America                        459
Independence Tournament             453
CONCACAF Championship               427
Asian Cup                           402
Gulf Cup                            382
European Championship               380
South American Champ                378
World Cup and African Cup qual      322
World Cup and Asian Cup qual        315
Name: count, dtype: int64